import React, {useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Calculator, Car, ChevronRight, CircleDollarSign, Clock3, CreditCard, Fuel, Gauge, Home, Landmark, Menu, Moon, Percent, PiggyBank, ReceiptIndianRupee, RotateCcw, Settings2, Sparkles, Sun, TrendingUp, WalletCards, X} from 'lucide-react';
import {AreaChart, Area, ResponsiveContainer, Tooltip, XAxis} from 'recharts';
import './styles.css';

type Tool = 'basic'|'fd'|'rd'|'sip'|'investment'|'petrol';
const tools:{id:Tool;label:string;sub:string;icon:any}[]=[
 {id:'basic',label:'Calculator',sub:'Everyday math',icon:Calculator},
 {id:'fd',label:'FD Calculator',sub:'Fixed deposit',icon:Landmark},
 {id:'rd',label:'RD Calculator',sub:'Recurring deposit',icon:WalletCards},
 {id:'sip',label:'SIP Calculator',sub:'Monthly investing',icon:TrendingUp},
 {id:'investment',label:'Investment',sub:'Growth & returns',icon:PiggyBank},
 {id:'petrol',label:'Petrol Cost',sub:'Trip fuel estimate',icon:Fuel},
];
const money=(n:number)=>'₹'+Math.round(n||0).toLocaleString('en-IN');
const pct=(n:number)=>`${Number(n).toFixed(2)}%`;

function App(){
 const [active,setActive]=useState<Tool>('basic'); const [dark,setDark]=useState(()=>localStorage.getItem('fyntrack-theme')!=='light'); const [mobile,setMobile]=useState(false); React.useEffect(()=>{localStorage.setItem('fyntrack-theme',dark?'dark':'light')},[dark]);
 return <div className={dark?'app dark':'app'}>
  <aside className={mobile?'sidebar open':'sidebar'}>
   <div className="brand"><div className="brandMark"><Sparkles size={17}/></div><div><b>fyntrack</b><span>Smart money tools</span></div><button className="close" onClick={()=>setMobile(false)}><X size={18}/></button></div>
   <div className="sideLabel">TOOLS</div>
   <nav>{tools.map(t=>{const I=t.icon;return <button key={t.id} className={active===t.id?'nav active':'nav'} onClick={()=>{setActive(t.id);setMobile(false)}}><span className="navIcon"><I size={18}/></span><span className="navText"><strong>{t.label}</strong><small>{t.sub}</small></span>{active===t.id&&<ChevronRight size={15} className="arrow"/>}</button>})}</nav>
   <div className="sideBottom"><div className="miniCard"><div className="miniIcon"><Gauge size={16}/></div><div><b>Built for decisions</b><span>Fast, clear & private</span></div></div><button className="nav muted"><span className="navIcon"><Settings2 size={18}/></span><span className="navText"><strong>Preferences</strong><small>Coming soon</small></span></button></div>
  </aside>
  <main className="main">
   <header><button className="menu" onClick={()=>setMobile(true)}><Menu/></button><div className="crumb"><span>Workspace</span><ChevronRight size={14}/><b>{tools.find(x=>x.id===active)?.label}</b></div><div className="headerActions"><span className="status"><i/>Calculations run locally</span><button className="theme" onClick={()=>setDark(!dark)}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button></div></header>
   <section className="content"><div className="quickStats"><div><span>TOOLS</span><b>06</b><small>Ready to use</small></div><div><span>MODE</span><b>{dark?"DARK":"LIGHT"}</b><small>Saved automatically</small></div><div><span>PRIVACY</span><b>LOCAL</b><small>No server calculation</small></div></div><div className="hero"><div><div className="eyebrow"><Sparkles size={14}/> SIMPLE FINANCE, BETTER DECISIONS</div><h1>{tools.find(x=>x.id===active)?.label}</h1><p>{active==='basic'?'A clean everyday calculator, without the clutter.':'Model your numbers with a premium, decision-first calculator.'}</p></div><div className="heroBadge"><CircleDollarSign size={19}/><span>₹ INR</span><i>•</i><span>Instant</span></div></div>
    {active==='basic'&&<Basic/>}{active==='fd'&&<FD/>}{active==='rd'&&<RD/>}{active==='sip'&&<SIP/>}{active==='investment'&&<Investment/>}{active==='petrol'&&<Petrol/>}
   </section>
   <footer><span>fyntrack · v0.2</span><span>Made for clarity, not complexity.</span></footer>
  </main>
 </div>
}

function Panel({children,title,icon:Icon}:{children:React.ReactNode;title:string;icon:any}){return <div className="panel"><div className="panelTitle"><div className="panelIcon"><Icon size={17}/></div><b>{title}</b></div>{children}</div>}
function Field({label,value,set,unit='₹',min=0,max=10000000,step=1}:{label:string;value:number;set:(n:number)=>void;unit?:string;min?:number;max?:number;step?:number}){return <label className="field"><span>{label}<em>{unit}</em></span><div className="input"><input type="number" value={value} min={min} max={max} step={step} onChange={e=>set(Number(e.target.value))}/><small>{unit}</small></div></label>}
function Slider({value,set,min,max,step=1}:{value:number;set:(n:number)=>void;min:number;max:number;step?:number}){return <input className="slider" type="range" value={value} min={min} max={max} step={step} onChange={e=>set(Number(e.target.value))}/>}
function Result({label,value,accent=false}:{label:string;value:string;accent?:boolean}){return <div className={accent?'result primary':'result'}><span>{label}</span><b>{value}</b></div>}

function Basic(){const [expr,setExpr]=useState('');const [result,setResult]=useState('0'); const keys=['7','8','9','÷','4','5','6','×','1','2','3','−','0','.','%','+']; const press=(k:string)=>{if(k==='=')return; if(k==='C'){setExpr('');setResult('0');return} if(k==='⌫'){setExpr(x=>x.slice(0,-1));return} setExpr(x=>x+k)}; const calculate=()=>{try{let s=expr.replaceAll('×','*').replaceAll('÷','/').replaceAll('−','-').replace(/%/g,'/100'); if(!/^[0-9+\-*/().\s]+$/.test(s))throw Error(); const r=Function(`"use strict";return (${s})`)(); setResult(Number.isFinite(r)?String(r):'Error')}catch{setResult('Error')}}; return <div className="basicGrid"><Panel title="Quick calculation" icon={Calculator}><div className="calc"><div className="display"><small>{expr||'Ready'}</small><strong>{result}</strong></div><div className="calcKeys">{keys.map(k=><button key={k} onClick={()=>press(k)}>{k}</button>)}<button className="clear" onClick={()=>press('C')}>C</button><button onClick={()=>press('⌫')}>⌫</button><button className="equals" onClick={calculate}>=</button></div></div></Panel><Panel title="Useful shortcuts" icon={Sparkles}><div className="shortcutList"><div><b>Tip</b><span>Use your keyboard for faster calculations.</span></div><div><b>Percent</b><span>Example: 500 + 10% → use % as a fraction.</span></div><div><b>Private</b><span>No numbers are sent to a server.</span></div></div></Panel></div>}

function FD(){const [p,setP]=useState(100000),[r,setR]=useState(7.25),[y,setY]=useState(3);const maturity=p*Math.pow(1+r/400,4*y);const interest=maturity-p;return <FinanceLayout title="Fixed Deposit" subtitle="Estimate maturity value using quarterly compounding." icon={Landmark} inputs={<><Field label="Principal" value={p} set={setP}/><Field label="Interest rate" value={r} set={setR} unit="%" max={30} step={.05}/><Field label="Tenure" value={y} set={setY} unit="Years" max={30}/></>} result={<><Result label="Maturity value" value={money(maturity)} accent/><Result label="Interest earned" value={money(interest)}/><Result label="Effective return" value={pct((interest/p)*100)}/></>} chart={<GrowthChart principal={p} final={maturity} years={y}/>}/>} 
function RD(){const [m,setM]=useState(5000),[r,setR]=useState(7),[y,setY]=useState(5);const n=y*12;const i=r/100/4;const maturity=m*((Math.pow(1+i,n)-1)/i)*(1+i);const interest=maturity-m*n;return <FinanceLayout title="Recurring Deposit" subtitle="See how disciplined monthly deposits can grow." icon={WalletCards} inputs={<><Field label="Monthly deposit" value={m} set={setM}/><Field label="Interest rate" value={r} set={setR} unit="%" max={30} step={.05}/><Field label="Tenure" value={y} set={setY} unit="Years" max={20}/></>} result={<><Result label="Maturity value" value={money(maturity)} accent/><Result label="Total deposited" value={money(m*n)}/><Result label="Interest earned" value={money(interest)}/></>} chart={<GrowthChart principal={m} final={maturity} years={y} monthly/>}/>} 
function SIP(){const [m,setM]=useState(10000),[r,setR]=useState(12),[y,setY]=useState(10);const n=y*12, mr=r/1200;const invested=m*n;const value=mr?m*((Math.pow(1+mr,n)-1)/mr)*(1+mr):invested;return <FinanceLayout title="SIP Calculator" subtitle="Project the future value of your monthly investments." icon={TrendingUp} inputs={<><Field label="Monthly investment" value={m} set={setM}/><Field label="Expected return" value={r} set={setR} unit="% p.a." max={40} step={.1}/><Field label="Investment period" value={y} set={setY} unit="Years" max={40}/></>} result={<><Result label="Future value" value={money(value)} accent/><Result label="Amount invested" value={money(invested)}/><Result label="Estimated gains" value={money(value-invested)}/></>} chart={<GrowthChart principal={invested} final={value} years={y} monthly/>}/>} 
function Investment(){const [p,setP]=useState(200000),[r,setR]=useState(12),[y,setY]=useState(10);const value=p*Math.pow(1+r/100,y),gain=value-p;return <FinanceLayout title="Investment Growth" subtitle="A simple compounding view for a one-time investment." icon={PiggyBank} inputs={<><Field label="Initial investment" value={p} set={setP}/><Field label="Expected annual return" value={r} set={setR} unit="%" max={50} step={.1}/><Field label="Holding period" value={y} set={setY} unit="Years" max={50}/></>} result={<><Result label="Future value" value={money(value)} accent/><Result label="Initial capital" value={money(p)}/><Result label="Wealth created" value={money(gain)}/></>} chart={<GrowthChart principal={p} final={value} years={y}/>}/>} 
function Petrol(){const [d,setD]=useState(300),[eff,setEff]=useState(15),[price,setPrice]=useState(96.5),[people,setPeople]=useState(1);const liters=d/eff,cost=liters*price,per=cost/Math.max(1,people);return <FinanceLayout title="Petrol Cost" subtitle="Know the fuel budget before you hit the road." icon={Fuel} inputs={<><Field label="Trip distance" value={d} set={setD} unit="km" max={10000}/><Field label="Vehicle mileage" value={eff} set={setEff} unit="km/L" max={100} step={.1}/><Field label="Petrol price" value={price} set={setPrice} unit="₹/L" max={300} step={.1}/><Field label="Travellers" value={people} set={setPeople} unit="People" min={1} max={20}/></>} result={<><Result label="Estimated fuel cost" value={money(cost)} accent/><Result label="Fuel required" value={`${liters.toFixed(1)} L`}/><Result label="Cost per person" value={money(per)}/></>} chart={<div className="tripVisual"><div className="route"><span>START</span><i/><span>DESTINATION</span></div><div className="tripStats"><div><Fuel size={17}/><b>{liters.toFixed(1)} L</b><small>Fuel needed</small></div><div><ReceiptIndianRupee size={17}/><b>{money(cost)}</b><small>Trip budget</small></div></div></div>}/>} 
function FinanceLayout({title,subtitle,icon,inputs,result,chart}:{title:string;subtitle:string;icon:any;inputs:React.ReactNode;result:React.ReactNode;chart:React.ReactNode}){const Icon=icon;return <div className="financeGrid"><Panel title="Your inputs" icon={Icon}><div className="fields">{inputs}</div><div className="rangeHint"><span>Adjust values above</span><span><RotateCcw size={13}/> Instant calculation</span></div></Panel><div className="rightStack"><Panel title="Your result" icon={CircleDollarSign}><div className="results">{result}</div></Panel><Panel title="Growth view" icon={TrendingUp}>{chart}</Panel></div></div>}
function GrowthChart({principal,final,years,monthly=false}:{principal:number;final:number;years:number;monthly?:boolean}){const data=Array.from({length:Math.min(12,Math.max(2,Math.round(years)+1))},(_,i)=>{const t=i*years/11;const v=principal+(final-principal)*(t/years);return {year:`${Math.round(t)}y`,value:v}});return <div className="chart"><div className="chartTop"><span>Projected value</span><b>{money(final)}</b></div><div className="chartBox"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data}><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopOpacity={.3}/><stop offset="100%" stopOpacity={0}/></linearGradient></defs><XAxis dataKey="year" axisLine={false} tickLine={false} tick={{fontSize:11}}/><Tooltip formatter={(v)=>money(Number(v))}/><Area type="monotone" dataKey="value" strokeWidth={2.5} fill="url(#g)"/></AreaChart></ResponsiveContainer></div><div className="chartFoot"><span>{monthly?'Monthly compounding illustration':'Compounding illustration'}</span><span>{years} years</span></div></div>}

createRoot(document.getElementById('root')!).render(<App/>);
