import React, { useEffect, useLayoutEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import {
  ArrowRight, BarChart3, Calculator, Car, ChevronDown, ChevronRight, CircleDollarSign,
  Contact, CreditCard, FileText, Fuel, Gauge, Home as HomeIcon, Landmark, Lock, Menu, Moon, Percent,
  PiggyBank, ReceiptIndianRupee, Search, ShieldCheck, Sparkles, Sun, Target, TrendingUp,
  WalletCards, X, Zap, IndianRupee, Info, Mail, BookOpen, LogIn
} from 'lucide-react';
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import './styles.css';

type CalcId = 'basic'|'fd'|'rd'|'sip'|'lumpsum'|'swp'|'mutualfund'|'cagr'|'compound'|'ppf'|'nps'|'retirement'|'emi'|'loaneligibility'|'tax'|'salary'|'gst'|'inflation'|'epf'|'gratuity'|'petrol';
type View = 'home'|'calculators'|'about'|'contact'|'privacy'|'terms'|'disclaimer'|'login';

type IconComponent = React.ComponentType<{size?: number; className?: string}>;
type CalcDef = {id:CalcId; label:string; desc:string; group:string; icon:IconComponent};
const calculators:CalcDef[] = [
 {id:'basic',label:'Smart Calculator',desc:'Everyday calculations',group:'Essentials',icon:Calculator},
 {id:'sip',label:'SIP Calculator',desc:'Monthly investment returns',group:'Investments',icon:TrendingUp},
 {id:'lumpsum',label:'Lumpsum Calculator',desc:'One-time investment growth',group:'Investments',icon:PiggyBank},
 {id:'swp',label:'SWP Calculator',desc:'Plan systematic withdrawals',group:'Investments',icon:WalletCards},
 {id:'mutualfund',label:'Mutual Fund Return Calculator',desc:'Measure mutual fund performance',group:'Investments',icon:BarChart3},
 {id:'cagr',label:'CAGR Calculator',desc:'Annualized investment growth',group:'Investments',icon:TrendingUp},
 {id:'compound',label:'Compound Interest Calculator',desc:'See how compounding grows money',group:'Investments',icon:CircleDollarSign},
 {id:'ppf',label:'PPF Calculator',desc:'Long-term PPF maturity estimate',group:'Savings & Deposits',icon:Landmark},
 {id:'fd',label:'FD Calculator',desc:'Fixed deposit maturity',group:'Savings & Deposits',icon:Landmark},
 {id:'rd',label:'RD Calculator',desc:'Recurring deposit growth',group:'Savings & Deposits',icon:WalletCards},
 {id:'epf',label:'EPF Calculator',desc:'Estimate provident fund corpus',group:'Savings & Deposits',icon:Landmark},
 {id:'nps',label:'NPS Calculator',desc:'Retirement corpus estimate',group:'Retirement & Planning',icon:BarChart3},
 {id:'retirement',label:'Retirement Calculator',desc:'Plan your retirement corpus',group:'Retirement & Planning',icon:Target},
 {id:'emi',label:'EMI Calculator',desc:'Home, car & personal loan EMI',group:'Loans & Credit',icon:CreditCard},
 {id:'loaneligibility',label:'Loan Eligibility Calculator',desc:'Estimate affordable loan amount',group:'Loans & Credit',icon:Gauge},
 {id:'tax',label:'Income Tax Calculator',desc:'Estimate income tax under the new regime',group:'Tax & Salary',icon:ReceiptIndianRupee},
 {id:'salary',label:'Salary Calculator',desc:'Estimate monthly take-home basis',group:'Tax & Salary',icon:ReceiptIndianRupee},
 {id:'gst',label:'GST Calculator',desc:'Inclusive & exclusive GST',group:'Tax & Salary',icon:IndianRupee},
 {id:'gratuity',label:'Gratuity Calculator',desc:'Estimate gratuity payout',group:'Tax & Salary',icon:WalletCards},
 {id:'inflation',label:'Inflation Calculator',desc:'Future purchasing power',group:'Everyday Finance',icon:Percent},
 {id:'petrol',label:'Petrol Cost Calculator',desc:'Trip fuel budget',group:'Everyday Finance',icon:Fuel},
];
const money=(n:number)=>'₹'+Math.round(Number.isFinite(n)?n:0).toLocaleString('en-IN');
const pct=(n:number)=>`${(Number.isFinite(n)?n:0).toFixed(2)}%`;
const calcById=(id:CalcId)=>calculators.find(c=>c.id===id)!;

function useHash():[View,CalcId]{
 const parse=():[View,CalcId]=>{
   const raw=location.hash.replace(/^#\/?/,'')||'home';
   const parts=raw.split('/');
   const v=parts[0] as View;
   const allowed:View[]=['home','calculators','about','contact','privacy','terms','disclaimer','login'];
   return [allowed.includes(v)?v:'home',(parts[1] as CalcId)||'basic'];
 };
 const [state,setState]=useState<[View,CalcId]>(parse);
 useEffect(()=>{const h=()=>setState(parse()); addEventListener('hashchange',h); return()=>removeEventListener('hashchange',h)},[]); return state;
}
function go(path:string){if(location.hash!==`#/${path}`) location.hash=path; else window.dispatchEvent(new HashChangeEvent('hashchange'));}

function App(){
 const [view,routeCalc]=useHash();
 const [dark,setDark]=useState(()=>localStorage.getItem('fyntrack-theme')!=='light');
 const [calcOpen,setCalcOpen]=useState(false);
 const [mobile,setMobile]=useState(false);
 useEffect(()=>{localStorage.setItem('fyntrack-theme',dark?'dark':'light'); document.documentElement.dataset.theme=dark?'dark':'light'},[dark]);
 useEffect(()=>{setCalcOpen(false);setMobile(false)},[view,routeCalc]);
 useLayoutEffect(()=>{window.scrollTo({top:0,left:0,behavior:'auto'})},[view,routeCalc]);
 return <div className={dark?'site dark':'site'} data-route={view}>
   <Header dark={dark} setDark={setDark} calcOpen={calcOpen} setCalcOpen={setCalcOpen} mobile={mobile} setMobile={setMobile}/>
   <RouteContent view={view} routeCalc={routeCalc}/>
   <Footer/>
 </div>
}

function RouteContent({view,routeCalc}:{view:View;routeCalc:CalcId}){
 const key=`${view}:${routeCalc}`;
 return <div className="routeRoot" data-route={view} key={key}>
   {view==='home' && <Home/>}
   {view==='calculators' && <CalculatorWorkspace active={routeCalc}/>}
   {view==='about' && <InfoPage title="About FynTrack" icon={Info}><p>FynTrack is a finance tools platform designed to make everyday money decisions easier to understand. We build calculators that turn inputs into clear, practical estimates without unnecessary complexity.</p><h2>Our approach</h2><p>We focus on transparent formulas, useful assumptions, clean interfaces and privacy-first calculations. Results are estimates for educational and planning purposes and should not be treated as financial advice.</p><div className="infoGrid"><InfoCard icon={Zap} title="Fast" text="Instant calculations with a lightweight interface."/><InfoCard icon={ShieldCheck} title="Private by design" text="Calculator inputs are processed in your browser."/><InfoCard icon={Target} title="Decision focused" text="Useful outputs, not distracting dashboards."/></div></InfoPage>}
   {view==='contact' && <ContactPage/>}
   {view==='privacy' && <LegalPage title="Privacy Policy"><h2>Information we collect</h2><p>FynTrack is designed so that calculator inputs can be processed locally in your browser. We do not require an account to use public calculators.</p><h2>Analytics and advertising</h2><p>As the website grows, we may use privacy-conscious analytics and third-party advertising services such as Google AdSense. These services may use cookies or similar technologies according to their own policies.</p><h2>Cookies</h2><p>Cookies may be used for site functionality, preferences, analytics or advertising. You can manage cookies through your browser settings.</p><h2>Third-party links</h2><p>External websites have their own privacy practices. FynTrack is not responsible for third-party content or policies.</p><p className="updated">Last updated: September 2026</p></LegalPage>}
   {view==='terms' && <LegalPage title="Terms of Use"><h2>Use of the website</h2><p>You may use FynTrack for personal, educational and general planning purposes. Do not misuse, disrupt or attempt to compromise the website.</p><h2>Calculator results</h2><p>Calculators provide estimates based on the inputs and assumptions shown. Actual returns, rates, taxes, fees and outcomes may differ.</p><h2>No financial advice</h2><p>FynTrack does not provide personalized investment, tax, legal or financial advice. Consider consulting a qualified professional for decisions involving your money.</p><h2>Changes</h2><p>We may improve, replace or remove tools and content as the platform develops.</p><p className="updated">Last updated: September 2026</p></LegalPage>}
   {view==='disclaimer' && <LegalPage title="Disclaimer"><div className="notice"><ShieldCheck size={20}/><div><b>Important</b><span>FynTrack calculators are informational tools, not financial advice.</span></div></div><p>Interest rates, taxation rules, market returns, fuel prices, loan terms and other variables can change. Always verify important figures with the relevant bank, lender, government authority or financial professional.</p><p>We aim to keep formulas and information useful and accurate, but we do not guarantee that every result will match a financial institution's calculation.</p></LegalPage>}
   {view==='login' && <Login/>}
 </div>
}

function Header({dark,setDark,calcOpen,setCalcOpen,mobile,setMobile}:{dark:boolean;setDark:(v:boolean)=>void;calcOpen:boolean;setCalcOpen:(v:boolean)=>void;mobile:boolean;setMobile:(v:boolean)=>void}){
 return <><header className="topbar"><div className="navWrap"><button className="mobileMenu" onClick={()=>setMobile(true)}><Menu/></button><button className="brand" onClick={()=>go('home')}><img src={`${import.meta.env.BASE_URL}fyntrack-logo.png`} alt="FynTrack"/><span>FynTrack</span></button><nav className="desktopNav"><button onClick={()=>{go('home');setTimeout(()=>document.getElementById('calculator-hub')?.scrollIntoView({behavior:'smooth',block:'start'}),60)}}>Features</button><div className="calcMenu"><button className="calcTrigger" onClick={()=>setCalcOpen(!calcOpen)}>Calculators <ChevronDown size={15}/></button>{calcOpen&&<CalculatorMegaMenu/>}</div></nav><div className="headerRight"><button className="iconBtn" aria-label="Toggle theme" onClick={()=>setDark(!dark)}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button><button className="loginBtn" onClick={()=>go('login')}><LogIn size={16}/> Login</button></div></div></header>{mobile&&<MobileMenu close={()=>setMobile(false)}/>}</>
}
function CalculatorMegaMenu(){return <div className="megaMenu"><div className="megaIntro"><div className="eyebrow"><Sparkles size={13}/> FYNTRACK TOOLS</div><b>Money calculators</b><span>Everything you need to model everyday finance.</span><button onClick={()=>go('calculators')}>Open calculator hub <ArrowRight size={15}/></button></div><div className="megaCols">{['Essentials','Investments','Savings & Deposits','Loans & Credit','Tax & Salary','Retirement & Planning','Everyday Finance'].map(group=><div key={group}><small>{group}</small>{calculators.filter(c=>c.group===group).slice(0,4).map(c=><button key={c.id} onClick={()=>go(`calculators/${c.id}`)}>{React.createElement(c.icon,{size:16})}{c.label}</button>)}</div>)}</div></div>}
function MobileMenu({close}:{close:()=>void}){return <div className="mobileOverlay"><aside className="mobilePanel"><div className="mobileHead"><button className="brand" onClick={()=>{go('home');close()}}><img src={`${import.meta.env.BASE_URL}fyntrack-logo.png`} alt=""/><span>FynTrack</span></button><button className="iconBtn" onClick={close}><X/></button></div><button onClick={()=>{go('home');close();setTimeout(()=>document.getElementById('calculator-hub')?.scrollIntoView({behavior:'smooth'}),60)}}>Features</button><button onClick={()=>{go('calculators');close()}}>All Calculators</button>{calculators.slice(0,8).map(c=><button key={c.id} onClick={()=>{go(`calculators/${c.id}`);close()}}>{React.createElement(c.icon,{size:17})}{c.label}</button>)}<hr/><button onClick={()=>{go('contact');close()}}>Contact</button><button onClick={()=>{go('login');close()}}>Login</button></aside></div>}

function Home(){return <main className="homePage"><section className="heroHome"><div className="heroGlow glowA"/><div className="heroGlow glowB"/><div className="heroCopy"><div className="pill"><span className="liveDot"/> Smart finance tools · Built for clarity</div><h1>Make smarter money decisions with <em>FynTrack.</em></h1><p>Professional calculators for savings, investments, loans and everyday finance — beautifully organized in one place.</p><div className="heroActions"><button className="primaryBtn" onClick={()=>go('calculators')}>Explore calculators <ArrowRight size={17}/></button><button className="ghostBtn" onClick={()=>go('about')}>How FynTrack works</button></div><div className="trustRow"><span><ShieldCheck size={15}/> Browser-first calculations</span><span><Zap size={15}/> Instant results</span><span><Lock size={15}/> No account required</span></div></div><Hero3D/></section>
<section className="statsBand"><div><b>20+</b><span>Finance tools</span></div><div><b>100%</b><span>Instant calculations</span></div><div><b>₹ INR</b><span>India-ready defaults</span></div><div><b>0</b><span>Forced sign-ups</span></div></section>
<section className="section" id="calculator-hub"><div className="sectionHead"><div><div className="eyebrow"><Calculator size={14}/> CALCULATOR HUB</div><h2>Everyday finance, one workspace.</h2><p>Pick a tool and get a clean, decision-ready estimate without navigating through a dozen separate sites.</p></div><button className="textBtn" onClick={()=>go('calculators')}>View all tools <ArrowRight size={16}/></button></div><div className="featureGrid">{calculators.slice(0,6).map((c,i)=><CalculatorCard key={c.id} c={c} featured={i===0}/>)}</div></section>
<section className="darkSection"><div className="sectionHead"><div><div className="eyebrow light"><Sparkles size={14}/> BUILT TO SCALE</div><h2>A finance platform, not just a calculator.</h2><p>Start with calculations today. Add trackers, planning tools and personalized features later without rebuilding the foundation.</p></div></div><div className="roadmap"><RoadCard n="01" title="Calculate" text="Model a decision with transparent inputs and useful outputs."/><RoadCard n="02" title="Compare" text="Understand contributions, interest, gains and trade-offs."/><RoadCard n="03" title="Track" text="Bring recurring financial goals into one place as the platform evolves."/></div></section>
<section className="section ctaSection"><div className="ctaCard"><div className="orbMini"><TrendingUp size={28}/></div><div><div className="eyebrow">NEXT-GEN PERSONAL FINANCE</div><h2>Your numbers deserve a better interface.</h2><p>Use FynTrack to turn a rough question into a clear financial estimate in seconds.</p></div><button className="primaryBtn" onClick={()=>go('calculators')}>Start calculating <ArrowRight size={17}/></button></div></section>
</main>}
function Hero3D(){return <div className="heroVisual"><div className="scene"><div className="orb"><div className="orbCore">₹</div><span className="ring ring1"/><span className="ring ring2"/></div><div className="floatCard cardA"><TrendingUp size={17}/><div><b>12.4%</b><span>Projected growth</span></div></div><div className="floatCard cardB"><CircleDollarSign size={17}/><div><b>₹2.84L</b><span>Future value</span></div></div><div className="floatCard cardC"><Gauge size={16}/><div><b>Instant</b><span>Local calculation</span></div></div></div></div>}
function CalculatorCard({c,featured}:{c:CalcDef;featured?:boolean}){const I=c.icon;return <button className={featured?'toolCard featured':'toolCard'} onClick={()=>go(`calculators/${c.id}`)}><div className="toolIcon"><I size={20}/></div><div><b>{c.label}</b><span>{c.desc}</span></div><ArrowRight size={17} className="toolArrow"/></button>}
function RoadCard({n,title,text}:{n:string;title:string;text:string}){return <div className="roadCard"><span>{n}</span><div><b>{title}</b><p>{text}</p></div></div>}

function CalculatorWorkspace({active}:{active:CalcId}){const [query,setQuery]=useState('');const groups=useMemo(()=>Array.from(new Set(calculators.map(c=>c.group))),[]); const shown=calculators.filter(c=>`${c.label} ${c.desc}`.toLowerCase().includes(query.toLowerCase())); return <main className="calcPage"><aside className="calcSidebar"><div className="sideTop"><div className="eyebrow"><Calculator size={13}/> TOOLBOX</div><h3>Calculators</h3><p>Professional money tools in one workspace.</p><div className="searchBox"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search calculators"/></div></div><div className="calcNav">{groups.map(g=>{const items=shown.filter(c=>c.group===g); if(!items.length)return null; return <div key={g}><small>{g}</small>{items.map(c=><button key={c.id} className={active===c.id?'calcNavItem active':'calcNavItem'} onClick={()=>go(`calculators/${c.id}`)}>{React.createElement(c.icon,{size:16})}<span>{c.label}</span>{active===c.id&&<ChevronRight size={14}/>}</button>)}</div>})}</div><div className="sideNote"><ShieldCheck size={16}/><div><b>Private by default</b><span>Inputs stay in your browser.</span></div></div></aside><section className="calcWorkspace"><div className="workspaceTop"><div><div className="eyebrow"><Sparkles size={13}/> FYNTRACK CALCULATOR</div><h1>{calcById(active).label}</h1><p>{calcById(active).desc}. Built for quick, transparent estimates.</p></div><button className="backHome" onClick={()=>go('home')}><HomeIcon size={16}/> Home</button></div>{active==='basic'?<Basic/>:active==='fd'?<FD/>:active==='rd'?<RD/>:active==='sip'?<SIP/>:active==='lumpsum'?<Lumpsum/>:active==='swp'?<SWP/>:active==='mutualfund'?<MutualFund/>:active==='cagr'?<CAGR/>:active==='compound'?<CompoundInterest/>:active==='ppf'?<PPF/>:active==='nps'?<NPS/>:active==='retirement'?<Retirement/>:active==='emi'?<EMI/>:active==='loaneligibility'?<LoanEligibility/>:active==='tax'?<IncomeTax/>:active==='salary'?<Salary/>:active==='gst'?<GST/>:active==='gratuity'?<Gratuity/>:active==='inflation'?<Inflation/>:active==='epf'?<EPF/>:<Petrol/>}</section></main>}

function Panel({children,title,icon:Icon,accent=false}:{children:React.ReactNode;title:string;icon:IconComponent;accent?:boolean}){return <div className={accent?'panel accentPanel':'panel'}><div className="panelTitle"><span className="panelIcon"><Icon size={16}/></span><b>{title}</b></div>{children}</div>}
function Field({label,value,set,unit='₹',min=0,max=10000000,step=1}:{label:string;value:number;set:(n:number)=>void;unit?:string;min?:number;max?:number;step?:number}){return <label className="field"><span>{label}</span><div className="input"><input type="number" value={value} min={min} max={max} step={step} onChange={e=>set(Number(e.target.value))}/><small>{unit}</small></div></label>}
function Duration({years,setYears,months,setMonths,maxYears}:{years:number;setYears:(n:number)=>void;months:number;setMonths:(n:number)=>void;maxYears:number}){return <div className="duration"><div><b>Duration</b><span>Choose years and additional months</span></div><div className="durationGrid"><Field label="Years" value={years} set={setYears} unit="Years" max={maxYears}/><Field label="Months" value={months} set={setMonths} unit="Months" max={11}/></div></div>}
function Result({label,value,accent=false,sub}:{label:string;value:string;accent?:boolean;sub?:string}){return <div className={accent?'result primary':'result'}><span>{label}</span><b>{value}</b>{sub&&<small>{sub}</small>}</div>}
function FinanceLayout({title,icon,inputs,results,chart}:{title:string;icon:IconComponent;inputs:React.ReactNode;results:React.ReactNode;chart:React.ReactNode}){const I=icon;return <div className="financeLayout"><div className="inputCol"><Panel title="Your inputs" icon={I}><div className="fields">{inputs}</div><div className="instant"><Zap size={14}/><span>Updates instantly as you type</span><i/></div></Panel><div className="formulaNote"><Info size={15}/><span>Estimates use standard mathematical formulas. Actual bank, lender or market outcomes can differ.</span></div></div><div className="resultCol"><Panel title="Your result" icon={CircleDollarSign} accent><div className="results">{results}</div></Panel><Panel title="Projection" icon={TrendingUp}>{chart}</Panel></div></div>}
function GrowthChart({principal,final,years,monthly=false}:{principal:number;final:number;years:number;monthly?:boolean}){const points=Math.min(14,Math.max(4,Math.round(years)+1));const data=Array.from({length:points},(_,i)=>{const t=years*(i/(points-1));const v=principal+(final-principal)*Math.pow(i/(points-1),1.35);return {period:`${t.toFixed(t<1?1:0)}y`,value:v}});return <div className="chart"><div className="chartMeta"><div><span>Projected value</span><b>{money(final)}</b></div><span>{monthly?'Monthly investment illustration':'Compounding illustration'}</span></div><div className="chartBox"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data}><defs><linearGradient id="fynFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopOpacity={.28}/><stop offset="100%" stopOpacity={0}/></linearGradient></defs><XAxis dataKey="period" axisLine={false} tickLine={false} tick={{fontSize:10}}/><YAxis hide/><Tooltip formatter={(v)=>money(Number(v))}/><Area type="monotone" dataKey="value" strokeWidth={2.5} fill="url(#fynFill)"/></AreaChart></ResponsiveContainer></div></div>}

function Basic(){const [expr,setExpr]=useState('');const [result,setResult]=useState('0');const keys=['7','8','9','÷','4','5','6','×','1','2','3','−','0','.','%','+'];const press=(k:string)=>{if(k==='C'){setExpr('');setResult('0');return}if(k==='⌫'){setExpr(x=>x.slice(0,-1));return}setExpr(x=>x+k)};const calc=()=>{try{const s=expr.replaceAll('×','*').replaceAll('÷','/').replaceAll('−','-').replace(/%/g,'/100');if(!/^[0-9+\-*/().\s]+$/.test(s))throw Error();const r=Function(`"use strict";return (${s})`)();setResult(Number.isFinite(r)?String(r):'Error')}catch{setResult('Error')}};return <div className="basicLayout"><Panel title="Quick calculation" icon={Calculator}><div className="calculator"><div className="display"><small>{expr||'Ready for your calculation'}</small><strong>{result}</strong></div><div className="keys">{keys.map(k=><button key={k} onClick={()=>press(k)}>{k}</button>)}<button className="clear" onClick={()=>press('C')}>C</button><button onClick={()=>press('⌫')}>⌫</button><button className="equals" onClick={calc}>=</button></div></div></Panel><Panel title="Why use FynTrack?" icon={ShieldCheck}><div className="benefitList"><div><Zap/><b>Instant</b><span>No page reloads.</span></div><div><Lock/><b>Private</b><span>Calculations stay local.</span></div><div><Gauge/><b>Readable</b><span>Results designed for decisions.</span></div></div></Panel></div>}

function FD(){const [p,setP]=useState(100000),[r,setR]=useState(7.25),[y,setY]=useState(3),[m,setM]=useState(0);const t=y+m/12,v=p*Math.pow(1+r/400,4*t),interest=v-p;return <FinanceLayout title="FD" icon={Landmark} inputs={<><Field label="Principal" value={p} set={setP}/><Field label="Interest rate" value={r} set={setR} unit="% p.a." max={30} step={.05}/><Duration years={y} setYears={setY} months={m} setMonths={setM} maxYears={30}/></>} results={<><Result label="Maturity value" value={money(v)} accent/><Result label="Interest earned" value={money(interest)}/><Result label="Total invested" value={money(p)}/></>} chart={<GrowthChart principal={p} final={v} years={t}/>}/>}
function RD(){const [m,setM]=useState(5000),[r,setR]=useState(7),[y,setY]=useState(5),[mo,setMo]=useState(0);const n=Math.max(0,y*12+mo),mr=Math.pow(1+r/400,1/3)-1,v=mr?m*((Math.pow(1+mr,n)-1)/mr)*(1+mr):m*n,dep=m*n;return <FinanceLayout title="RD" icon={WalletCards} inputs={<><Field label="Monthly deposit" value={m} set={setM}/><Field label="Interest rate" value={r} set={setR} unit="% p.a." max={30} step={.05}/><Duration years={y} setYears={setY} months={mo} setMonths={setMo} maxYears={20}/></>} results={<><Result label="Maturity value" value={money(v)} accent/><Result label="Total deposited" value={money(dep)}/><Result label="Interest earned" value={money(v-dep)}/></>} chart={<GrowthChart principal={dep} final={v} years={n/12} monthly/>}/>}
function SIP(){const [m,setM]=useState(10000),[r,setR]=useState(12),[y,setY]=useState(10),[mo,setMo]=useState(0);const n=Math.max(0,y*12+mo),mr=r/1200,invested=m*n,v=mr?m*((Math.pow(1+mr,n)-1)/mr)*(1+mr):invested;return <FinanceLayout title="SIP" icon={TrendingUp} inputs={<><Field label="Monthly investment" value={m} set={setM}/><Field label="Expected return" value={r} set={setR} unit="% p.a." max={50} step={.1}/><Duration years={y} setYears={setY} months={mo} setMonths={setMo} maxYears={40}/></>} results={<><Result label="Future value" value={money(v)} accent/><Result label="Amount invested" value={money(invested)}/><Result label="Estimated gains" value={money(v-invested)}/></>} chart={<GrowthChart principal={invested} final={v} years={n/12} monthly/>}/>}
function Lumpsum(){const [p,setP]=useState(200000),[r,setR]=useState(12),[y,setY]=useState(10),[m,setM]=useState(0);const t=y+m/12,v=p*Math.pow(1+r/100,t);return <FinanceLayout title="Lumpsum" icon={PiggyBank} inputs={<><Field label="Initial investment" value={p} set={setP}/><Field label="Expected return" value={r} set={setR} unit="% p.a." max={50} step={.1}/><Duration years={y} setYears={setY} months={m} setMonths={setM} maxYears={50}/></>} results={<><Result label="Future value" value={money(v)} accent/><Result label="Initial capital" value={money(p)}/><Result label="Wealth created" value={money(v-p)}/></>} chart={<GrowthChart principal={p} final={v} years={t}/>}/>}
function PPF(){const [dep,setDep]=useState(100000),[r,setR]=useState(7.1),[y,setY]=useState(15);const rate=r/100;let bal=0;const data=[];for(let i=1;i<=Math.max(1,y);i++){bal=(bal+dep)*(1+rate);data.push({period:`${i}y`,value:bal})}const v=bal,invested=dep*y;return <FinanceLayout title="PPF" icon={Landmark} inputs={<><Field label="Yearly contribution" value={dep} set={setDep} max={150000}/><Field label="Interest rate" value={r} set={setR} unit="% p.a." max={15} step={.05}/><Field label="Tenure" value={y} set={setY} unit="Years" min={1} max={50}/></>} results={<><Result label="Estimated maturity" value={money(v)} accent/><Result label="Total contribution" value={money(invested)}/><Result label="Estimated interest" value={money(v-invested)}/></>} chart={<GrowthChart principal={invested} final={v} years={y}/>}/>}
function NPS(){const [m,setM]=useState(10000),[r,setR]=useState(10),[y,setY]=useState(25);const mr=r/1200,n=y*12,invested=m*n,v=mr?m*((Math.pow(1+mr,n)-1)/mr)*(1+mr):invested;return <FinanceLayout title="NPS" icon={BarChart3} inputs={<><Field label="Monthly contribution" value={m} set={setM}/><Field label="Expected return" value={r} set={setR} unit="% p.a." max={30} step={.1}/><Field label="Investment period" value={y} set={setY} unit="Years" min={1} max={50}/></>} results={<><Result label="Estimated corpus" value={money(v)} accent/><Result label="Total contribution" value={money(invested)}/><Result label="Estimated growth" value={money(v-invested)}/></>} chart={<GrowthChart principal={invested} final={v} years={y} monthly/>}/>}
function EMI(){const [p,setP]=useState(1000000),[r,setR]=useState(8.5),[y,setY]=useState(20);const n=y*12,mr=r/1200,emi=mr?p*mr*Math.pow(1+mr,n)/(Math.pow(1+mr,n)-1):p/n,total=emi*n;return <FinanceLayout title="EMI" icon={CreditCard} inputs={<><Field label="Loan amount" value={p} set={setP}/><Field label="Interest rate" value={r} set={setR} unit="% p.a." max={40} step={.05}/><Field label="Tenure" value={y} set={setY} unit="Years" min={1} max={40}/></>} results={<><Result label="Monthly EMI" value={money(emi)} accent/><Result label="Total interest" value={money(total-p)}/><Result label="Total payment" value={money(total)}/></>} chart={<PaymentSplit principal={p} interest={total-p}/>}/>}
function PaymentSplit({principal,interest}:{principal:number;interest:number}){const data=[{name:'Principal',value:principal},{name:'Interest',value:Math.max(0,interest)}];return <div className="split"><div className="splitValue"><b>{money(principal+interest)}</b><span>Total repayment</span></div><div className="splitBar"><i style={{width:`${principal/Math.max(1,principal+interest)*100}%`}}/><i style={{width:`${interest/Math.max(1,principal+interest)*100}%`}}/></div><div className="splitLegend"><span>Principal <b>{money(principal)}</b></span><span>Interest <b>{money(interest)}</b></span></div></div>}
function Inflation(){const [p,setP]=useState(100000),[r,setR]=useState(6),[y,setY]=useState(10);const future=p*Math.pow(1+r/100,y),today=p/Math.pow(1+r/100,y);return <FinanceLayout title="Inflation" icon={Percent} inputs={<><Field label="Current amount" value={p} set={setP}/><Field label="Inflation rate" value={r} set={setR} unit="% p.a." max={30} step={.1}/><Field label="Period" value={y} set={setY} unit="Years" min={1} max={50}/></>} results={<><Result label="Future equivalent cost" value={money(future)} accent/><Result label="Today's ₹100,000 becomes" value={money(future)}/><Result label="Today's value of future amount" value={money(today)}/></>} chart={<GrowthChart principal={p} final={future} years={y}/>}/>}
function Petrol(){const [d,setD]=useState(300),[eff,setEff]=useState(15),[price,setPrice]=useState(96.5),[people,setPeople]=useState(1);const liters=eff?d/eff:0,cost=liters*price;return <FinanceLayout title="Petrol Cost" icon={Fuel} inputs={<><Field label="Trip distance" value={d} set={setD} unit="km" max={10000}/><Field label="Vehicle mileage" value={eff} set={setEff} unit="km/L" max={100} step={.1}/><Field label="Petrol price" value={price} set={setPrice} unit="₹/L" max={300} step={.1}/><Field label="Travellers" value={people} set={setPeople} unit="People" min={1} max={20}/></>} results={<><Result label="Estimated fuel cost" value={money(cost)} accent/><Result label="Fuel required" value={`${liters.toFixed(1)} L`}/><Result label="Cost per person" value={money(cost/Math.max(1,people))}/></>} chart={<div className="tripModule"><div className="road"><span>START</span><i/><span>DESTINATION</span></div><div className="tripCards"><div><Fuel/><b>{liters.toFixed(1)} L</b><span>Fuel required</span></div><div><CircleDollarSign/><b>{money(cost)}</b><span>Trip budget</span></div></div></div>}/>}
function Salary(){const [annual,setAnnual]=useState(1200000),[bonus,setBonus]=useState(0),[ded,setDed]=useState(50000);const taxable=Math.max(0,annual+bonus-ded),monthly=taxable/12;return <FinanceLayout title="Salary" icon={ReceiptIndianRupee} inputs={<><Field label="Annual CTC" value={annual} set={setAnnual}/><Field label="Annual bonus" value={bonus} set={setBonus}/><Field label="Annual deductions" value={ded} set={setDed}/></>} results={<><Result label="Estimated monthly basis" value={money(monthly)} accent/><Result label="Estimated annual taxable basis" value={money(taxable)}/><Result label="Effective deduction input" value={pct((ded/Math.max(1,annual))*100)}/></>} chart={<div className="salaryModule"><div><span>Annual CTC</span><b>{money(annual)}</b></div><div><span>Monthly basis</span><b>{money(monthly)}</b></div><small>Illustrative only — actual take-home depends on tax regime, PF, employer structure and other deductions.</small></div>}/>}
function GST(){const [amount,setAmount]=useState(10000),[rate,setRate]=useState(18);const gst=amount*rate/100,total=amount+gst,base=amount/(1+rate/100),embedded=amount-base;return <FinanceLayout title="GST" icon={IndianRupee} inputs={<><Field label="Amount" value={amount} set={setAmount}/><Field label="GST rate" value={rate} set={setRate} unit="%" max={40} step={.5}/></>} results={<><Result label="GST amount (exclusive)" value={money(gst)} accent/><Result label="Total with GST" value={money(total)}/><Result label="Base from inclusive amount" value={money(base)}/><Result label="GST embedded" value={money(embedded)}/></>} chart={<div className="gstVisual"><div><span>Base</span><b>{money(base)}</b></div><div><span>GST</span><b>{money(embedded)}</b></div><div><span>Total</span><b>{money(amount)}</b></div></div>}/>}


function SWP(){const [initial,setInitial]=useState(1000000),[withdrawal,setWithdrawal]=useState(10000),[r,setR]=useState(10),[y,setY]=useState(10);const n=y*12,mr=r/1200;let bal=initial;for(let i=0;i<n;i++)bal=Math.max(0,bal*(1+mr)-withdrawal);const total=withdrawal*n;return <FinanceLayout title="SWP" icon={WalletCards} inputs={<><Field label="Starting corpus" value={initial} set={setInitial}/><Field label="Monthly withdrawal" value={withdrawal} set={setWithdrawal}/><Field label="Expected return" value={r} set={setR} unit="% p.a." max={30} step={.1}/><Field label="Withdrawal period" value={y} set={setY} unit="Years" min={1} max={50}/></>} results={<><Result label="Estimated ending corpus" value={money(bal)} accent/><Result label="Total withdrawals" value={money(total)}/><Result label="Starting corpus" value={money(initial)}/></>} chart={<GrowthChart principal={initial} final={bal} years={y}/>}/>}
function MutualFund(){const [invested,setInvested]=useState(200000),[value,setValue]=useState(275000),[y,setY]=useState(3),[m,setM]=useState(0);const t=y+m/12,profit=value-invested,cagr=t>0?(Math.pow(Math.max(.000001,value/invested),1/t)-1)*100:0,roi=invested?profit/invested*100:0;return <FinanceLayout title="Mutual Fund Returns" icon={BarChart3} inputs={<><Field label="Total invested" value={invested} set={setInvested}/><Field label="Current value" value={value} set={setValue}/><Duration years={y} setYears={setY} months={m} setMonths={setM} maxYears={50}/></>} results={<><Result label="Profit / loss" value={money(profit)} accent/><Result label="Absolute return" value={pct(roi)}/><Result label="Annualized return (CAGR)" value={pct(cagr)}/></>} chart={<GrowthChart principal={invested} final={value} years={t}/>}/>}
function CAGR(){const [initial,setInitial]=useState(100000),[final,setFinal]=useState(180000),[y,setY]=useState(5),[m,setM]=useState(0);const t=y+m/12,cagr=t>0?(Math.pow(Math.max(.000001,final/initial),1/t)-1)*100:0;return <FinanceLayout title="CAGR" icon={TrendingUp} inputs={<><Field label="Initial value" value={initial} set={setInitial}/><Field label="Final value" value={final} set={setFinal}/><Duration years={y} setYears={setY} months={m} setMonths={setM} maxYears={50}/></>} results={<><Result label="CAGR" value={pct(cagr)} accent/><Result label="Absolute gain" value={money(final-initial)}/><Result label="Final value" value={money(final)}/></>} chart={<GrowthChart principal={initial} final={final} years={t}/>}/>}
function CompoundInterest(){const [p,setP]=useState(100000),[a,setA]=useState(5000),[r,setR]=useState(10),[y,setY]=useState(10),[m,setM]=useState(0);const t=y+m/12,n=Math.max(0,y*12+m),mr=r/1200,v=p*Math.pow(1+r/100,t)+(mr?a*((Math.pow(1+mr,n)-1)/mr)*(1+mr):a*n),invested=p+a*n;return <FinanceLayout title="Compound Interest" icon={CircleDollarSign} inputs={<><Field label="Initial principal" value={p} set={setP}/><Field label="Monthly contribution" value={a} set={setA}/><Field label="Interest rate" value={r} set={setR} unit="% p.a." max={50} step={.1}/><Duration years={y} setYears={setY} months={m} setMonths={setM} maxYears={50}/></>} results={<><Result label="Future value" value={money(v)} accent/><Result label="Total invested" value={money(invested)}/><Result label="Compound growth" value={money(v-invested)}/></>} chart={<GrowthChart principal={invested} final={v} years={t} monthly/>}/>}
function Retirement(){const [current,setCurrent]=useState(500000),[m,setM]=useState(15000),[r,setR]=useState(10),[y,setY]=useState(25),[infl,setInfl]=useState(6);const n=y*12,mr=r/1200,v= current*Math.pow(1+r/100,y)+(mr?m*((Math.pow(1+mr,n)-1)/mr)*(1+mr):m*n),real=v/Math.pow(1+infl/100,y);return <FinanceLayout title="Retirement" icon={Target} inputs={<><Field label="Current retirement savings" value={current} set={setCurrent}/><Field label="Monthly investment" value={m} set={setM}/><Field label="Expected return" value={r} set={setR} unit="% p.a." max={30} step={.1}/><Field label="Years to retirement" value={y} set={setY} unit="Years" min={1} max={50}/><Field label="Inflation rate" value={infl} set={setInfl} unit="% p.a." max={20} step={.1}/></>} results={<><Result label="Estimated retirement corpus" value={money(v)} accent/><Result label="Total contributions" value={money(current+m*n)}/><Result label="Today's purchasing power" value={money(real)}/></>} chart={<GrowthChart principal={current} final={v} years={y} monthly/>}/>}
function LoanEligibility(){const [income,setIncome]=useState(100000),[obligations,setObligations]=useState(10000),[foir,setFoir]=useState(50),[r,setR]=useState(8.5),[y,setY]=useState(20);const affordable=Math.max(0,income*foir/100-obligations),n=y*12,mr=r/1200,loan=mr>0?affordable*(1-Math.pow(1+mr,-n))/mr:affordable*n;return <FinanceLayout title="Loan Eligibility" icon={Gauge} inputs={<><Field label="Monthly income" value={income} set={setIncome}/><Field label="Existing monthly EMIs" value={obligations} set={setObligations}/><Field label="FOIR / EMI capacity" value={foir} set={setFoir} unit="%" min={20} max={80} step={1}/><Field label="Interest rate" value={r} set={setR} unit="% p.a." max={30} step={.05}/><Field label="Tenure" value={y} set={setY} unit="Years" min={1} max={40}/></>} results={<><Result label="Estimated eligible loan" value={money(loan)} accent/><Result label="Estimated affordable EMI" value={money(affordable)}/><Result label="Existing EMI load" value={money(obligations)}/></>} chart={<div className="salaryModule"><div><span>Monthly income</span><b>{money(income)}</b></div><div><span>Estimated EMI capacity</span><b>{money(affordable)}</b></div><small>Illustrative eligibility estimate. Actual lender limits depend on credit profile, income type, age, rate and policy.</small></div>}/>}
function IncomeTax(){const [income,setIncome]=useState(1200000),[deduction,setDeduction]=useState(75000);const taxable=Math.max(0,income-deduction);let tax=0;const slabs=[[400000,0],[800000,.05],[1200000,.10],[1600000,.15],[2000000,.20],[2400000,.25],[Infinity,.30]];let prev=0;for(const [limit,rate] of slabs){const amt=Math.max(0,Math.min(taxable,limit)-prev);tax+=amt*rate;prev=limit;if(taxable<=limit)break}const rebate=taxable<=1200000?Math.min(tax,60000):0;const net=Math.max(0,tax-rebate),cess=net*.04,total=net+cess;return <FinanceLayout title="Income Tax" icon={ReceiptIndianRupee} inputs={<><Field label="Annual gross income" value={income} set={setIncome}/><Field label="Eligible deductions" value={deduction} set={setDeduction}/></>} results={<><Result label="Estimated tax + cess" value={money(total)} accent/><Result label="Tax before cess" value={money(net)}/><Result label="Taxable income" value={money(taxable)}/></>} chart={<div className="salaryModule"><div><span>Taxable income</span><b>{money(taxable)}</b></div><div><span>Estimated tax</span><b>{money(total)}</b></div><small>Illustrative new-regime estimate for AY 2026–27. It does not model every exemption, surcharge or special-rate income.</small></div>}/>}
function EPF(){const [employee,setEmployee]=useState(5000),[employer,setEmployer]=useState(5000),[r,setR]=useState(8.25),[y,setY]=useState(25);const n=y*12,mr=r/1200,monthly=employee+employer,v=mr?monthly*((Math.pow(1+mr,n)-1)/mr)*(1+mr):monthly*n;return <FinanceLayout title="EPF" icon={Landmark} inputs={<><Field label="Employee contribution / month" value={employee} set={setEmployee}/><Field label="Employer contribution / month" value={employer} set={setEmployer}/><Field label="Interest rate" value={r} set={setR} unit="% p.a." max={15} step={.05}/><Field label="Service period" value={y} set={setY} unit="Years" min={1} max={45}/></>} results={<><Result label="Estimated EPF corpus" value={money(v)} accent/><Result label="Total contributions" value={money(monthly*n)}/><Result label="Estimated interest" value={money(v-monthly*n)}/></>} chart={<GrowthChart principal={monthly*n} final={v} years={y} monthly/>}/>}
function Gratuity(){const [salary,setSalary]=useState(50000),[years,setYears]=useState(10);const completed=Math.max(0,Math.floor(years)),amount=salary*15/26*completed;return <FinanceLayout title="Gratuity" icon={WalletCards} inputs={<><Field label="Last drawn basic + DA" value={salary} set={setSalary}/><Field label="Completed years of service" value={years} set={setYears} unit="Years" min={1} max={50}/></>} results={<><Result label="Estimated gratuity" value={money(amount)} accent/><Result label="Completed service years" value={String(completed)}/><Result label="Formula" value="15 / 26 × salary × years"/></>} chart={<div className="salaryModule"><div><span>Basic + DA</span><b>{money(salary)}</b></div><div><span>Estimated gratuity</span><b>{money(amount)}</b></div><small>Illustrative estimate using the standard 15/26 formula. Eligibility and applicable rules can vary.</small></div>}/>}

function ContactPage(){
 const [sent,setSent]=useState(false);
 const [form,setForm]=useState({name:'',email:'',topic:'General feedback',message:''});
 const update=(key:keyof typeof form,value:string)=>setForm(prev=>({...prev,[key]:value}));
 const submit=(e:React.FormEvent)=>{e.preventDefault(); const subject=encodeURIComponent(`[FynTrack] ${form.topic}`); const body=encodeURIComponent(`Name: ${form.name}\nEmail: ${form.email}\nTopic: ${form.topic}\n\n${form.message}`); window.location.href=`mailto:support@masterminddivyansh.github.io/fyntrack?subject=${subject}&body=${body}`; setSent(true);};
 return <main className="contactPage">
   <section className="contactHero"><div><div className="eyebrow"><Mail size={13}/> FYNTRACK · CONTACT</div><h1>Let's build a better<br/><em>money experience.</em></h1><p>Found an issue, have a calculator idea, or want to share feedback? Send us a clear note and we'll take a look.</p><div className="contactTrust"><span><ShieldCheck size={15}/> Privacy-conscious</span><span><Zap size={15}/> Quick to submit</span><span><Lock size={15}/> No account required</span></div></div><div className="contactOrb"><div className="contactOrbCore"><Mail size={28}/></div><span className="contactOrbit o1"/><span className="contactOrbit o2"/></div></section>
   <section className="contactShell">
    <div className="contactAside"><div className="contactMini"><span className="miniIcon"><Mail size={17}/></span><div><b>Email support</b><a href="mailto:support@masterminddivyansh.github.io/fyntrack">support@masterminddivyansh.github.io/fyntrack</a><small>General questions, corrections and product feedback.</small></div></div><div className="contactMini"><span className="miniIcon"><Calculator size={17}/></span><div><b>Calculator issue?</b><small>Include the calculator, inputs and what you expected to see.</small></div></div><div className="contactMini"><span className="miniIcon"><ShieldCheck size={17}/></span><div><b>No sensitive data</b><small>Please don't include passwords, bank details or other confidential financial information.</small></div></div></div>
    <form className="contactForm" onSubmit={submit}><div className="formHeader"><div><span className="formKicker">SEND A MESSAGE</span><h2>How can we help?</h2></div><span className="formStatus"><i/> Usually replies by email</span></div><div className="formGrid"><label><span>Your name</span><input required value={form.name} onChange={e=>update('name',e.target.value)} placeholder="Enter your name" autoComplete="name"/></label><label><span>Email address</span><input required type="email" value={form.email} onChange={e=>update('email',e.target.value)} placeholder="you@example.com" autoComplete="email"/></label><label className="full"><span>What is this about?</span><select value={form.topic} onChange={e=>update('topic',e.target.value)}><option>General feedback</option><option>Calculator correction</option><option>Bug report</option><option>Calculator suggestion</option><option>Business enquiry</option><option>Privacy request</option></select></label><label className="full"><span>Message</span><textarea required value={form.message} onChange={e=>update('message',e.target.value)} placeholder="Tell us what you found or what you'd like to see…" rows={6}/></label></div><div className="formBottom"><span><Lock size={13}/> Your message opens in your email client.</span><button className="primaryBtn" type="submit">Send message <ArrowRight size={16}/></button></div>{sent&&<div className="formSuccess"><ShieldCheck size={16}/><span>Your email client should now be open with the message prepared.</span></div>}</form>
   </section>
 </main>
}

function InfoPage({title,icon:Icon,children}:{title:string;icon:IconComponent;children:React.ReactNode}){return <main className="simplePage"><div className="pageHero"><span className="largeIcon"><Icon/></span><div><div className="eyebrow">FYNTRACK</div><h1>{title}</h1><p>Clear information for a trustworthy finance tools platform.</p></div></div><article className="articleCard">{children}</article></main>}
function LegalPage({title,children}:{title:string;children:React.ReactNode}){return <main className="simplePage"><div className="legalTop"><FileText size={20}/><div><span>FYNTRACK · LEGAL</span><h1>{title}</h1></div></div><article className="articleCard">{children}</article></main>}
function InfoCard({icon:Icon,title,text}:{icon:IconComponent;title:string;text:string}){return <div className="infoCard"><Icon/><b>{title}</b><span>{text}</span></div>}
function Login(){return <main className="loginPage"><div className="loginCard"><div className="loginLogo"><img src={`${import.meta.env.BASE_URL}fyntrack-logo.png`} alt="FynTrack"/></div><div className="eyebrow">FYNTRACK ACCOUNT</div><h1>Personal finance, eventually.</h1><p>Accounts are not active yet. Public calculators are fully available without signing in.</p><button className="primaryBtn" disabled><LogIn size={17}/> Login — Coming soon</button><button className="outlineBtn" disabled>Create account — Coming soon</button><div className="loginNote"><Lock size={14}/> We will never require an account just to calculate.</div></div></main>}
function Footer(){return <footer className="footer"><div className="footerMain"><div><button className="footerBrand" onClick={()=>go('home')}><img src={`${import.meta.env.BASE_URL}fyntrack-logo.png`} alt=""/><b>FynTrack</b></button><p>Smart finance tools for everyday decisions.</p></div><div className="footerLinks"><div><b>Explore</b><button onClick={()=>go('calculators')}>Calculators</button><a href={`${import.meta.env.BASE_URL}about.html`}>About</a><button onClick={()=>go('contact')}>Contact</button></div><div><b>Legal</b><a href={`${import.meta.env.BASE_URL}privacy-policy.html`}>Privacy Policy</a><a href={`${import.meta.env.BASE_URL}terms.html`}>Terms of Use</a><a href={`${import.meta.env.BASE_URL}disclaimer.html`}>Disclaimer</a></div></div></div><div className="footerBottom"><span>© 2026 FynTrack. All rights reserved.</span><span>Calculations are estimates, not financial advice.</span></div></footer>}

createRoot(document.getElementById('root')!).render(<App/>);
